apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameservice }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
    nodePort: 30009
